version: "3.1"

services:
  db:
    restart: always
    image: dinkylink/db
    build:
      context: services/db
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["--auth"]
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./services/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:so
      - dinky_db_volume:/data/db
    networks:
      - dinky_net

  api:
    restart: always
    image: dinkylink/api
    build:
      context: services/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ./services/api/lib:/usr/src/app/lib:so
    depends_on:
      - db
    networks:
      - dinky_net

  ws:
    restart: always
    image: dinkylink/ws
    build:
      context: services/ws
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:8082:8082
    volumes:
      - ./services/ws/lib:/usr/src/app/lib:so
    depends_on:
      - db
    networks:
      - dinky_net

  ui:
    restart: always
    image: dinkylink/ui
    build:
      context: services/ui
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./services/ui/dist:/usr/src/app/dist:so
    depends_on:
      - api
    networks:
      - dinky_net

  proxy:
    restart: always
    image: nginx:1.25.2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:so
      - /etc/letsencrypt:/etc/letsencrypt:so
    depends_on:
      - api
      - ui
    networks:
      - dinky_net

  cache:
    restart: always
    image: redis:7.2.0-alpine
    # env_file:
    #   - .env
    ports:
      - 127.0.0.1:8083:6379
    volumes:
      - dinky_cache_volume:/data
    depends_on:
      - api
      - db
    networks:
      - dinky_net

  broker:
    restart: always
    image: redis:7.2.0-alpine
    # env_file:
    #   - .env
    ports:
      - 127.0.0.1:8084:6379
    volumes:
      - dinky_broker_volume:/data
    depends_on:
      - api
      - db
    networks:
      - dinky_net

volumes:
  dinky_db_volume:
  dinky_cache_volume:
  dinky_broker_volume:

networks:
  dinky_net:
    driver: bridge
