version: "3.1"

services:
  create_db:
    restart: always
    image: create_db
    build:
      context: db
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["--auth"]
    ports:
      - 127.0.0.1:${CREATE_DB_PORT}:${CREATE_DB_PORT}
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:so
      - create_db_volume:/data/db
    networks:
      - create_net

  create_api:
    restart: always
    image: create_api
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${CREATE_API_PORT}:${CREATE_API_PORT}
    depends_on:
      - create_db
    networks:
      - create_net

volumes:
  create_db_volume:

networks:
  create_net:
    driver: bridge
