import dotenv from "dotenv";

dotenv.config();

export const {
  VISIT_HOST,
  VISIT_PORT,
  UI_HOST,
  DB_HOST,
  DB_PORT,
  MONGO_USERNAME,
  MONGO_PASSWORD,
  MONGO_INITDB_DATABASE,
  CACHE_HOST,
  CACHE_PORT,
  CACHE_USER,
  CACHE_PASSWORD,
  STREAM_HOST,
  STREAM_PORT,
  STREAM_USER,
  STREAM_PASSWORD,
} = process.env;

export const DB_CONNECTION_STRING = `mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST}:${DB_PORT}/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}`;
export const STREAM_CONNECTION_STRING = `redis://${STREAM_HOST}:${STREAM_PORT}`;
export const CACHE_CONNECTION_STRING = `redis://${CACHE_HOST}:${CACHE_PORT}`;
